name = "Create"
author = "Filipsi"
version = "1.0.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4208dec6cc82ae74b941110c434c6bd00dee53a14c5411fda987966cfdc4385e"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
