name = "Create"
author = "Filipsi"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bb1f2d00dd19ea97ea46a8b3dafa5d7caeacfeb0d834c31c7b1ef5d21004511"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
