name = "Create"
author = "Filipsi"
version = "1.0.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f479aa59e6e508e97f10be09545322700bd326ef736c7ff0d1bf45669efac3e2"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
