name = "Create"
author = "Filipsi"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bdff46e700759a63fb04ea006072da31713a34bc6809c4de8af7a50afe6ffc6"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
