name = "Create"
author = "Filipsi"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7b2d5edaa8690ea48b496d82dc7c3d204482cab7309f8278d95c3b6e61c9031"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
