name = "Create"
author = "Filipsi"
version = "1.0.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb52f32ea3c054244211d37f36caa366f75f1915098a4c8b6980fb7bb4104dcc"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
