name = "Create"
author = "Filipsi"
version = "1.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38ea320afbe60d1602faf45af727a3b2db880e352ed3ec4760ebb2d55a2d1e0a"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
