name = "Create"
author = "Filipsi"
version = "1.0.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5fef1601427b8125cbabc7972ada17890e66aa7e80956492c85bf53b3068118"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
