name = "Create"
author = "Filipsi"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3736b1baf2f6d1822e0535c8b95c2ff74bfab7164edfbe9bd3080334e24336bf"

[versions]
forge = "43.1.52"
minecraft = "1.19.2"
